[package]
name = "dao4j"
version = "0.1.0"
authors = ["ponyloop <anlaakso@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.6.0"

[lib]
name = "dao4j"
path = "lib.rs"
